In [ ]:
import pandas as pd

data = {
    'gender' :['male','female','female','male','female'],
    'city' :['mumbai','delhi','chennai','mumbai','delhi'],
    'size' :['small','large','medium','large','small'],
    'age' :[25,42,32,60,28],
    'fare' :[15,300,85,450,20]
}

df = pd.DataFrame(data)
df

   gender     city    size  age  fare
0    male   mumbai   small   25    15
1  female    delhi   large   42   300
2  female  chennai  medium   32    85
3    male   mumbai   large   60   450
4  female    delhi   small   28    20

In [ ]:
df['gender'] = df['gender'].map({'male':1,'female':0})
df

   gender     city    size  age  fare
0       1   mumbai   small   25    15
1       0    delhi   large   42   300
2       0  chennai  medium   32    85
3       1   mumbai   large   60   450
4       0    delhi   small   28    20

In [ ]:
df = pd.get_dummies(df,columns=['city'],drop_first=True)
df

   gender    size  age  fare  city_delhi  city_mumbai
0       1   small   25    15       False         True
1       0   large   42   300        True        False
2       0  medium   32    85       False        False
3       1   large   60   450       False         True
4       0   small   28    20        True        False

In [ ]:
size_mapping={'small':0,'medium':1,'large':2}
df['size']=df['size'].map(size_mapping)
df

   gender  size  age  fare  city_delhi  city_mumbai
0       1     0   25    15       False         True
1       0     2   42   300        True        False
2       0     1   32    85       False        False
3       1     2   60   450       False         True
4       0     0   28    20        True        False

In [ ]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df[['age','fare']]=scaler.fit_transform(df[['age','fare']])
df

   gender  size       age      fare  city_delhi  city_mumbai
0       1     0 -0.500000 -0.250000       False         True
1       0     2  0.714286  0.767857        True        False
2       0     1  0.000000  0.000000       False        False
3       1     2  2.000000  1.303571       False         True
4       0     0 -0.285714 -0.232143        True        False

RobustScaler is used because the fare column contains an outlier(450).
it scales data using mediun and iqr ,making it robust to extreme values.